config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, skip: [:sessions]
  as :user do
  	get 'signup', to: 'devise/registrations#new'
	  get 'signin', to: 'devise/sessions#new', as: :new_user_session
	  post 'signin', to: 'devise/sessions#create', as: :user_session
	  delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  resources :posts
  resources :users, only: [:show, :edit, :update]
  resources :comments, only: [:create]
  namespace 'api' do
    namespace 'v1' do
      resources :posts
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::ActiveStorage

  attr_accessor :data

  has_one_attached :storage_data
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_content
    rails_representation_url(storage_data.variant(resize: '800>').processed, only_path: true)
  end

  def url_thumb
    rails_representation_url(storage_data.variant(resize: '118x100').processed, only_path: true)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 16, maximum: 150}
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: {minimum: 6, maximum: 12}, uniqueness: true

  validates :first_name, presence: true, length: {minimum: 2, maximum: 10}

  validates :last_name, presence: true, 	length: {minimum: 2, maximum: 10}

  has_many :posts
  has_many :comments, dependent: :destroy
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :load_post, only: [:show]

  def index
    @posts = Post.order('created_at DESC')
    render json: {
      status: true,
      data: @posts
    }, 
    status: :ok
  end

  def show
    render json: {
      status: true,
      data: @post
    }, 
    status: :ok
  end

  private
  def load_post
    @post = Post.find_by id: params[:id]
    return if @post
    render json: {
      status: false,
      message: 'Not found'
    }, 
    status: :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def require_user
		if !user_signed_in?
			flash[:danger] ="You must be logged in to perform that action"
			redirect_to root_path
		end
	end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :gender, :first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :gender, :first_name, :last_name, :password_confirmation, :current_password])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_user
	def create
		@post = Post.find(comment_params[:post_id])
	    @comment = Comment.new(comment_params)
	    @comment.post = @post
	    @comment.user = current_user
	    if @comment.save
			respond_to do |format|
	          format.js
	        end
		else
			redirect_to post_path(@post)
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:content, :post_id)
	end

	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@posts = Post.limit(3).order('id desc')
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	def new
		@post = Post.new
	end

	def index
		# @post = Post.paginate(page: params[:page], per_page: 5)
		@posts = Post.limit(3).order('id desc')
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if @post.save
			flash[:success] = "Post was successfully created"
			# redirect_to post_path(@post)
			redirect_to root_path
		else
			render 'new'
		end
	end

	def show
		@comment = Comment.new
		@recent_posts = Post.limit(3).order('id desc')
	end	

	def edit
		
	end

	def update
		if @post.update(post_params)
			flash[:success] = "Post was successfully updated"
			# redirect_to post_path(@post)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		flash[:success] = "Post was successfully deletedd"
		redirect_to posts_path
	end

	private
	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end

	def require_same_user
		if current_user != @post.user
			flash[:danger] = "You can only edit or delete your own posts"
			redirect_to root_path
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	def show

	end

	def edit

	end

	def update

	end

	private
		def set_user
			@user = User.find(params[:id])
		end

		def user_params
			params.require(:user).permit(:email, :username, :firstn_name, :last_name, :gender, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comments.html.erb
		<div class="col-12"><%= cmt.content %></div>
		<div class="col-12">
			<strong>
				<small> 
				<%= link_to cmt.user.username, user_path(cmt.user) %> at <%=cmt.created_at.strftime("%F") %>
				</small>
			</strong>
		</div>
		

app/views/comments/_form.html.erb
<div class="container-fluid comment-body">
	<%= form_for comment, remote: true do |f| %>
	    <%= f.hidden_field :post_id, value: post.id %>
	    <div class="form-group">
	    	<%= f.text_area :content, class:"form-control", placeholder:"Write a comment" %>
	    </div>
	  	<%= f.submit "Send", class:"btn btn-success" %>
	<% end %>
</div>

app/views/comments/create.js.erb
$('.comment-row').prepend('<%= j render 'comments/comments', cmt: @comment %>');
$('#comment_content').val('');

app/views/layouts/_footer.html.erb
<div class="footer container mt-5">
	<hr/>
	<h3 class="text-center mb-3"><strong class="text-danger">X</strong>-Blog</h3>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="container">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">
          &#215;
        </a>
        <%= msg %>
      </div>
    <% end %>  
  </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="nav">
  <div class="container">
  <%= link_to '<h2 class="text-center"><strong class="text-danger">X</strong>-Blog</h2>'.html_safe, root_path, class:"w-100 mb-4" %>
  <hr/>
  
  <div class="row">
    <div class="col-lg-6 col-xs-12 m-auto">
      <ul class="menu-bar">
        <li><%= link_to 'Home', root_path, class:"active" %></li>
        <li><%= link_to 'Blog', posts_path %></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle p-0" data-toggle="dropdown"><i class="far fa-user"></i></a>
            <div class="dropdown-menu">
              <% if !user_signed_in? %>
                <%= link_to 'Sign In', new_user_session_path, class:"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to 'Sign Up', new_user_registration_path, class:"dropdown-item" %>
              <% else %>
                <%= link_to 'My Profile', user_path(current_user), class:"dropdown-item" %>
                <%= link_to 'New Post', new_post_path, class:"dropdown-item" %>

                <div class="dropdown-divider"></div>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"dropdown-item" %>

              <% end %>
            </div>
        </li>
      </ul>
    </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>

  </head>

  <body>
    <div class="container-fluid">
      <%= render 'layouts/nav' %>
      <%= render 'layouts/messages' %>
      <div class="wrapper">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="slider"></div>

<div class="latest-post">
	<div class="container">
		<h3 class="text-center">Latest Post</h3>
		<hr>
		<div class="latest-body">
			<div class="container-fluid">
				<% @posts.each do |item| %>
					<div class="row">
						<div class="col-12 mt-4 latest-item">
							<div class="item-header">
								<strong><p class="mb-0"> <%= item.title.truncate(200) %> </p></strong>
								<%= item.content.truncate(350).html_safe %>
							</div>
							<div class="item-info mt-1">
								<span class="far fa-comment"> <%= item.comments.count %></span>
								<small><p class="text-right d-inline float-right"><%= item.user.username %></p></small>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>
<div class="container">
	<%= form_for @post do |f| %>
		<div class="form-group ">
		    <%= f.label :title, class:"h4" %> <br/>
		    <%= f.text_field :title, class:"form-control", placeholder:"Enter title" %>
	    </div>
	    <div class="form-group">
		    <%= f.label :content, class:"h4" %> <br/>
		    <%= f.cktext_area :content, class:"form-control"%>
	    </div>
	    <%= f.submit class:"btn btn-success ml-auto" %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container post-list">
	<div class="row ml-0 mr-0">
		<% @posts.each do |item| %>
			<div class="col-12 post-item">
				<strong>
					<p class="m-0"> 
						<%= link_to item.title.truncate(100), post_path(item) %>
					 </p>
				</strong>
				<small>
					<%= item.user.username %> posted at <%= item.created_at.strftime('%F') %>
				</small>	
				<%= raw(item.content.truncate(160)) %>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
	<div class="row m-0 p-5 post-detail">
		<div class="col-12">
			<div class="row">
				<div class="col-12 post-header">
					<strong><h3 class="mb-0"><%= @post.title %></h3></strong>
					<small><%= @post.user.username%> posted at <%= @post.created_at.strftime("%F") %></small> 
				</div>
				<div class="col-12 mt-3 post-body text-justify">
					<%= raw(@post.content) %>
				</div>
			</div>
		</div>
	</div>
	<div class="row mt-5">
		<div class="col-12">
			<div class="recent-post">
				<div class="row ml-0 mr-0">
					<strong>Recent Post</strong>
					<hr>
					<% @recent_posts.each do |item| %>
						<div class="col-4 p-0 recent-post-item">
							<%= link_to post_path(item) do %>
								  <div class="card" style="width: 19rem;">
									  <div class="card-body" style="height: 10rem">
									    <h5 class="card-title text-justify mb-0" style="height: 5rem"><%= item.title.truncate(50) %></h5>
									    <h6 class="card-subtitle mb-2 text-muted"><%= item.user.username%></h6>
									    <small><p class="card-text"><%= item.comments.count %> Comment</p></small>
									  </div>
									</div>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="row mt-5 ml-0 mr-0 comment">
		<strong>Comments</strong>
		<hr>
		<div class="comment-row w-100">
		<% @post.comments.order('id desc').each do |cmt| %>
			
				<%= render 'comments/comments', cmt: cmt %>
			
		<% end %>
		</div>
	</div>
	<div class="row mt-5 ml-0 mr-0">
		<%= render 'comments/form', comment: @comment, post: @post if user_signed_in?%>
	</div>
</div>

app/views/shared/_errors.html.erb
<div class="container">
  <% if obj.errors.any? %>
    <div class="row mb-3">
      <div class="col-12">
        <div class="card text-white">
          <h5 class="card-header bg-danger">Oops..!</h5>
          <div class="card-body" style="background-color: #ec5858e0">
            <h5 class="card-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from being saved:
            </h5>
            <p class="card-text">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-lg-2">
			<strong><h4><%= @user.first_name%>'s Profile</h4></strong>
		</div>
		<div class="col-md-6 col-lg-10 text-right">
			 <%= link_to 'Create New Post', new_post_path, class:"text-white new-post-btn" %>
		</div>
	</div>
	<div class="row ml-0 mr-0">
		<div class="col-12 info-header p-3">
			Email: <%= @user.email %><br>
			Username: <%= @user.username %><br>
			Full Name: <%= @user.first_name %> <%= @user.last_name %>
		</div>
	</div>
	<div class="row ml-0 mr-0 mt-3">
		<div class="col-6 col-md-2 text-center info-body-tab active">
			<strong><p>Posts</p></strong>
		</div>
		<div class="col-6 col-md-2 text-center info-body-tab">
			<strong><p>Comments</p></strong>
		</div>
	</div>
	<hr style="border: 1px solid #e0dbdb; margin-top: -0.5px"/>
	<div class="row ml-0 mr-0">
		<% @user.posts.each do |post| %>
			<div class="col-12 info-post-item p-2 position-relative">
				<strong><p class="mb-2"><%= post.title %></p></strong>
				<%= link_to 'Edit', edit_post_path(post), class:"position-absolute edit-post-btn btn btn-secondary ", style:"top:10%; right: 2%" %>
				<%= raw(post.content.truncate(120)) %>
			</div>
		<% end %>
	</div>
</div>